#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak_Uygulaması
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Emlak")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIlan_Gorselleri(Ilan_Gorselleri instance);
    partial void UpdateIlan_Gorselleri(Ilan_Gorselleri instance);
    partial void DeleteIlan_Gorselleri(Ilan_Gorselleri instance);
    partial void InsertKiralik(Kiralik instance);
    partial void UpdateKiralik(Kiralik instance);
    partial void DeleteKiralik(Kiralik instance);
    partial void InsertSatilik(Satilik instance);
    partial void UpdateSatilik(Satilik instance);
    partial void DeleteSatilik(Satilik instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Emlak_Uygulaması.Properties.Settings.Default.EmlakConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ilan_Gorselleri> Ilan_Gorselleris
		{
			get
			{
				return this.GetTable<Ilan_Gorselleri>();
			}
		}
		
		public System.Data.Linq.Table<Kiralik> Kiraliks
		{
			get
			{
				return this.GetTable<Kiralik>();
			}
		}
		
		public System.Data.Linq.Table<Satilik> Satiliks
		{
			get
			{
				return this.GetTable<Satilik>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ilan_Gorselleri")]
	public partial class Ilan_Gorselleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ilan_No;
		
		private System.Data.Linq.Binary _Ilan_Gorselleri1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIlan_NoChanging(string value);
    partial void OnIlan_NoChanged();
    partial void OnIlan_Gorselleri1Changing(System.Data.Linq.Binary value);
    partial void OnIlan_Gorselleri1Changed();
    #endregion
		
		public Ilan_Gorselleri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_No", DbType="VarChar(50)")]
		public string Ilan_No
		{
			get
			{
				return this._Ilan_No;
			}
			set
			{
				if ((this._Ilan_No != value))
				{
					this.OnIlan_NoChanging(value);
					this.SendPropertyChanging();
					this._Ilan_No = value;
					this.SendPropertyChanged("Ilan_No");
					this.OnIlan_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ilan_Gorselleri", Storage="_Ilan_Gorselleri1", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Ilan_Gorselleri1
		{
			get
			{
				return this._Ilan_Gorselleri1;
			}
			set
			{
				if ((this._Ilan_Gorselleri1 != value))
				{
					this.OnIlan_Gorselleri1Changing(value);
					this.SendPropertyChanging();
					this._Ilan_Gorselleri1 = value;
					this.SendPropertyChanged("Ilan_Gorselleri1");
					this.OnIlan_Gorselleri1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kiralik")]
	public partial class Kiralik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _E_Kayit;
		
		private string _Ilan_Baslik;
		
		private string _Ilan_Tarih;
		
		private string _Ilan_Konum;
		
		private System.Data.Linq.Binary _Ilan_Temel_G;
		
		private string _Ucret;
		
		private string _Alan;
		
		private string _Bina_Yasi;
		
		private string _Kat_Sayisi;
		
		private string _Isitma;
		
		private string _Balkon;
		
		private string _Aidat;
		
		private string _Ilani_Veren;
		
		private string _Ilani_Veren_Tel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_KayitChanging(int value);
    partial void OnE_KayitChanged();
    partial void OnIlan_BaslikChanging(string value);
    partial void OnIlan_BaslikChanged();
    partial void OnIlan_TarihChanging(string value);
    partial void OnIlan_TarihChanged();
    partial void OnIlan_KonumChanging(string value);
    partial void OnIlan_KonumChanged();
    partial void OnIlan_Temel_GChanging(System.Data.Linq.Binary value);
    partial void OnIlan_Temel_GChanged();
    partial void OnUcretChanging(string value);
    partial void OnUcretChanged();
    partial void OnAlanChanging(string value);
    partial void OnAlanChanged();
    partial void OnBina_YasiChanging(string value);
    partial void OnBina_YasiChanged();
    partial void OnKat_SayisiChanging(string value);
    partial void OnKat_SayisiChanged();
    partial void OnIsitmaChanging(string value);
    partial void OnIsitmaChanged();
    partial void OnBalkonChanging(string value);
    partial void OnBalkonChanged();
    partial void OnAidatChanging(string value);
    partial void OnAidatChanged();
    partial void OnIlani_VerenChanging(string value);
    partial void OnIlani_VerenChanged();
    partial void OnIlani_Veren_TelChanging(string value);
    partial void OnIlani_Veren_TelChanged();
    #endregion
		
		public Kiralik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Kayit", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int E_Kayit
		{
			get
			{
				return this._E_Kayit;
			}
			set
			{
				if ((this._E_Kayit != value))
				{
					this.OnE_KayitChanging(value);
					this.SendPropertyChanging();
					this._E_Kayit = value;
					this.SendPropertyChanged("E_Kayit");
					this.OnE_KayitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Baslik", DbType="VarChar(150)")]
		public string Ilan_Baslik
		{
			get
			{
				return this._Ilan_Baslik;
			}
			set
			{
				if ((this._Ilan_Baslik != value))
				{
					this.OnIlan_BaslikChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Baslik = value;
					this.SendPropertyChanged("Ilan_Baslik");
					this.OnIlan_BaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Tarih", DbType="VarChar(50)")]
		public string Ilan_Tarih
		{
			get
			{
				return this._Ilan_Tarih;
			}
			set
			{
				if ((this._Ilan_Tarih != value))
				{
					this.OnIlan_TarihChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Tarih = value;
					this.SendPropertyChanged("Ilan_Tarih");
					this.OnIlan_TarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Konum", DbType="VarChar(120)")]
		public string Ilan_Konum
		{
			get
			{
				return this._Ilan_Konum;
			}
			set
			{
				if ((this._Ilan_Konum != value))
				{
					this.OnIlan_KonumChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Konum = value;
					this.SendPropertyChanged("Ilan_Konum");
					this.OnIlan_KonumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Temel_G", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Ilan_Temel_G
		{
			get
			{
				return this._Ilan_Temel_G;
			}
			set
			{
				if ((this._Ilan_Temel_G != value))
				{
					this.OnIlan_Temel_GChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Temel_G = value;
					this.SendPropertyChanged("Ilan_Temel_G");
					this.OnIlan_Temel_GChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ucret", DbType="VarChar(50)")]
		public string Ucret
		{
			get
			{
				return this._Ucret;
			}
			set
			{
				if ((this._Ucret != value))
				{
					this.OnUcretChanging(value);
					this.SendPropertyChanging();
					this._Ucret = value;
					this.SendPropertyChanged("Ucret");
					this.OnUcretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alan", DbType="VarChar(50)")]
		public string Alan
		{
			get
			{
				return this._Alan;
			}
			set
			{
				if ((this._Alan != value))
				{
					this.OnAlanChanging(value);
					this.SendPropertyChanging();
					this._Alan = value;
					this.SendPropertyChanged("Alan");
					this.OnAlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bina_Yasi", DbType="VarChar(50)")]
		public string Bina_Yasi
		{
			get
			{
				return this._Bina_Yasi;
			}
			set
			{
				if ((this._Bina_Yasi != value))
				{
					this.OnBina_YasiChanging(value);
					this.SendPropertyChanging();
					this._Bina_Yasi = value;
					this.SendPropertyChanged("Bina_Yasi");
					this.OnBina_YasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kat_Sayisi", DbType="VarChar(50)")]
		public string Kat_Sayisi
		{
			get
			{
				return this._Kat_Sayisi;
			}
			set
			{
				if ((this._Kat_Sayisi != value))
				{
					this.OnKat_SayisiChanging(value);
					this.SendPropertyChanging();
					this._Kat_Sayisi = value;
					this.SendPropertyChanged("Kat_Sayisi");
					this.OnKat_SayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isitma", DbType="VarChar(50)")]
		public string Isitma
		{
			get
			{
				return this._Isitma;
			}
			set
			{
				if ((this._Isitma != value))
				{
					this.OnIsitmaChanging(value);
					this.SendPropertyChanging();
					this._Isitma = value;
					this.SendPropertyChanged("Isitma");
					this.OnIsitmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balkon", DbType="VarChar(50)")]
		public string Balkon
		{
			get
			{
				return this._Balkon;
			}
			set
			{
				if ((this._Balkon != value))
				{
					this.OnBalkonChanging(value);
					this.SendPropertyChanging();
					this._Balkon = value;
					this.SendPropertyChanged("Balkon");
					this.OnBalkonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aidat", DbType="VarChar(50)")]
		public string Aidat
		{
			get
			{
				return this._Aidat;
			}
			set
			{
				if ((this._Aidat != value))
				{
					this.OnAidatChanging(value);
					this.SendPropertyChanging();
					this._Aidat = value;
					this.SendPropertyChanged("Aidat");
					this.OnAidatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilani_Veren", DbType="VarChar(50)")]
		public string Ilani_Veren
		{
			get
			{
				return this._Ilani_Veren;
			}
			set
			{
				if ((this._Ilani_Veren != value))
				{
					this.OnIlani_VerenChanging(value);
					this.SendPropertyChanging();
					this._Ilani_Veren = value;
					this.SendPropertyChanged("Ilani_Veren");
					this.OnIlani_VerenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilani_Veren_Tel", DbType="VarChar(50)")]
		public string Ilani_Veren_Tel
		{
			get
			{
				return this._Ilani_Veren_Tel;
			}
			set
			{
				if ((this._Ilani_Veren_Tel != value))
				{
					this.OnIlani_Veren_TelChanging(value);
					this.SendPropertyChanging();
					this._Ilani_Veren_Tel = value;
					this.SendPropertyChanged("Ilani_Veren_Tel");
					this.OnIlani_Veren_TelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Satilik")]
	public partial class Satilik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _E_Kayit;
		
		private string _Ilan_Baslik;
		
		private string _Ilan_Tarih;
		
		private string _Ilan_Konum;
		
		private System.Data.Linq.Binary _Ilan_Temel_G;
		
		private string _Ucret;
		
		private string _Alan;
		
		private string _Bina_Yasi;
		
		private string _Kat_Sayisi;
		
		private string _Isitma;
		
		private string _Balkon;
		
		private string _Aidat;
		
		private string _Ilani_Veren;
		
		private string _Ilani_Veren_Tel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_KayitChanging(int value);
    partial void OnE_KayitChanged();
    partial void OnIlan_BaslikChanging(string value);
    partial void OnIlan_BaslikChanged();
    partial void OnIlan_TarihChanging(string value);
    partial void OnIlan_TarihChanged();
    partial void OnIlan_KonumChanging(string value);
    partial void OnIlan_KonumChanged();
    partial void OnIlan_Temel_GChanging(System.Data.Linq.Binary value);
    partial void OnIlan_Temel_GChanged();
    partial void OnUcretChanging(string value);
    partial void OnUcretChanged();
    partial void OnAlanChanging(string value);
    partial void OnAlanChanged();
    partial void OnBina_YasiChanging(string value);
    partial void OnBina_YasiChanged();
    partial void OnKat_SayisiChanging(string value);
    partial void OnKat_SayisiChanged();
    partial void OnIsitmaChanging(string value);
    partial void OnIsitmaChanged();
    partial void OnBalkonChanging(string value);
    partial void OnBalkonChanged();
    partial void OnAidatChanging(string value);
    partial void OnAidatChanged();
    partial void OnIlani_VerenChanging(string value);
    partial void OnIlani_VerenChanged();
    partial void OnIlani_Veren_TelChanging(string value);
    partial void OnIlani_Veren_TelChanged();
    #endregion
		
		public Satilik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Kayit", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int E_Kayit
		{
			get
			{
				return this._E_Kayit;
			}
			set
			{
				if ((this._E_Kayit != value))
				{
					this.OnE_KayitChanging(value);
					this.SendPropertyChanging();
					this._E_Kayit = value;
					this.SendPropertyChanged("E_Kayit");
					this.OnE_KayitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Baslik", DbType="VarChar(150)")]
		public string Ilan_Baslik
		{
			get
			{
				return this._Ilan_Baslik;
			}
			set
			{
				if ((this._Ilan_Baslik != value))
				{
					this.OnIlan_BaslikChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Baslik = value;
					this.SendPropertyChanged("Ilan_Baslik");
					this.OnIlan_BaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Tarih", DbType="VarChar(50)")]
		public string Ilan_Tarih
		{
			get
			{
				return this._Ilan_Tarih;
			}
			set
			{
				if ((this._Ilan_Tarih != value))
				{
					this.OnIlan_TarihChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Tarih = value;
					this.SendPropertyChanged("Ilan_Tarih");
					this.OnIlan_TarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Konum", DbType="VarChar(120)")]
		public string Ilan_Konum
		{
			get
			{
				return this._Ilan_Konum;
			}
			set
			{
				if ((this._Ilan_Konum != value))
				{
					this.OnIlan_KonumChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Konum = value;
					this.SendPropertyChanged("Ilan_Konum");
					this.OnIlan_KonumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilan_Temel_G", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Ilan_Temel_G
		{
			get
			{
				return this._Ilan_Temel_G;
			}
			set
			{
				if ((this._Ilan_Temel_G != value))
				{
					this.OnIlan_Temel_GChanging(value);
					this.SendPropertyChanging();
					this._Ilan_Temel_G = value;
					this.SendPropertyChanged("Ilan_Temel_G");
					this.OnIlan_Temel_GChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ucret", DbType="VarChar(50)")]
		public string Ucret
		{
			get
			{
				return this._Ucret;
			}
			set
			{
				if ((this._Ucret != value))
				{
					this.OnUcretChanging(value);
					this.SendPropertyChanging();
					this._Ucret = value;
					this.SendPropertyChanged("Ucret");
					this.OnUcretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alan", DbType="VarChar(50)")]
		public string Alan
		{
			get
			{
				return this._Alan;
			}
			set
			{
				if ((this._Alan != value))
				{
					this.OnAlanChanging(value);
					this.SendPropertyChanging();
					this._Alan = value;
					this.SendPropertyChanged("Alan");
					this.OnAlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bina_Yasi", DbType="VarChar(50)")]
		public string Bina_Yasi
		{
			get
			{
				return this._Bina_Yasi;
			}
			set
			{
				if ((this._Bina_Yasi != value))
				{
					this.OnBina_YasiChanging(value);
					this.SendPropertyChanging();
					this._Bina_Yasi = value;
					this.SendPropertyChanged("Bina_Yasi");
					this.OnBina_YasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kat_Sayisi", DbType="VarChar(50)")]
		public string Kat_Sayisi
		{
			get
			{
				return this._Kat_Sayisi;
			}
			set
			{
				if ((this._Kat_Sayisi != value))
				{
					this.OnKat_SayisiChanging(value);
					this.SendPropertyChanging();
					this._Kat_Sayisi = value;
					this.SendPropertyChanged("Kat_Sayisi");
					this.OnKat_SayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isitma", DbType="VarChar(50)")]
		public string Isitma
		{
			get
			{
				return this._Isitma;
			}
			set
			{
				if ((this._Isitma != value))
				{
					this.OnIsitmaChanging(value);
					this.SendPropertyChanging();
					this._Isitma = value;
					this.SendPropertyChanged("Isitma");
					this.OnIsitmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balkon", DbType="VarChar(50)")]
		public string Balkon
		{
			get
			{
				return this._Balkon;
			}
			set
			{
				if ((this._Balkon != value))
				{
					this.OnBalkonChanging(value);
					this.SendPropertyChanging();
					this._Balkon = value;
					this.SendPropertyChanged("Balkon");
					this.OnBalkonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aidat", DbType="VarChar(50)")]
		public string Aidat
		{
			get
			{
				return this._Aidat;
			}
			set
			{
				if ((this._Aidat != value))
				{
					this.OnAidatChanging(value);
					this.SendPropertyChanging();
					this._Aidat = value;
					this.SendPropertyChanged("Aidat");
					this.OnAidatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilani_Veren", DbType="VarChar(50)")]
		public string Ilani_Veren
		{
			get
			{
				return this._Ilani_Veren;
			}
			set
			{
				if ((this._Ilani_Veren != value))
				{
					this.OnIlani_VerenChanging(value);
					this.SendPropertyChanging();
					this._Ilani_Veren = value;
					this.SendPropertyChanged("Ilani_Veren");
					this.OnIlani_VerenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilani_Veren_Tel", DbType="VarChar(50)")]
		public string Ilani_Veren_Tel
		{
			get
			{
				return this._Ilani_Veren_Tel;
			}
			set
			{
				if ((this._Ilani_Veren_Tel != value))
				{
					this.OnIlani_Veren_TelChanging(value);
					this.SendPropertyChanging();
					this._Ilani_Veren_Tel = value;
					this.SendPropertyChanged("Ilani_Veren_Tel");
					this.OnIlani_Veren_TelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
